import { Zone } from '../types';

// Sawai Mansingh Stadium - Jaipur, India
// Center coordinates: 26.8923, 75.8019

export const STADIUM_CENTER = { lat: 26.8923, lng: 75.8019 };

export const INITIAL_ZONES: Zone[] = [
  {
    id: 'gate-a',
    name: 'Gate A - Main Entry',
    type: 'entry_gate',
    capacity: 500,
    currentOccupancy: 120,
    predictedOccupancy: 180,
    status: 'clear',
    predictedStatus: 'moderate',
    waitTime: 2,
    predictedWaitTime: 5,
    congestionTrend: 'rising',
    riskScore: 0.24,
    coordinates: { lat: 26.8935, lng: 75.8005 },
    adjacentZones: ['corridor-north', 'parking-a'],
    lastUpdated: Date.now(),
  },
  {
    id: 'gate-b',
    name: 'Gate B - East Entry',
    type: 'entry_gate',
    capacity: 400,
    currentOccupancy: 310,
    predictedOccupancy: 370,
    status: 'crowded',
    predictedStatus: 'critical',
    waitTime: 12,
    predictedWaitTime: 18,
    congestionTrend: 'rising',
    riskScore: 0.78,
    coordinates: { lat: 26.8920, lng: 75.8040 },
    adjacentZones: ['corridor-east', 'parking-b'],
    lastUpdated: Date.now(),
  },
  {
    id: 'gate-c',
    name: 'Gate C - South Entry',
    type: 'entry_gate',
    capacity: 450,
    currentOccupancy: 200,
    predictedOccupancy: 230,
    status: 'moderate',
    predictedStatus: 'moderate',
    waitTime: 5,
    predictedWaitTime: 6,
    congestionTrend: 'stable',
    riskScore: 0.44,
    coordinates: { lat: 26.8908, lng: 75.8020 },
    adjacentZones: ['corridor-south', 'parking-c'],
    lastUpdated: Date.now(),
  },
  {
    id: 'gate-d',
    name: 'Gate D - VIP Entry',
    type: 'entry_gate',
    capacity: 200,
    currentOccupancy: 40,
    predictedOccupancy: 50,
    status: 'clear',
    predictedStatus: 'clear',
    waitTime: 1,
    predictedWaitTime: 1,
    congestionTrend: 'stable',
    riskScore: 0.1,
    coordinates: { lat: 26.8928, lng: 75.7998 },
    adjacentZones: ['vip-lounge', 'corridor-west'],
    lastUpdated: Date.now(),
  },
  {
    id: 'stand-north',
    name: 'North Stand',
    type: 'seating',
    capacity: 5000,
    currentOccupancy: 3200,
    predictedOccupancy: 4100,
    status: 'moderate',
    predictedStatus: 'crowded',
    waitTime: 0,
    predictedWaitTime: 0,
    congestionTrend: 'rising',
    riskScore: 0.64,
    coordinates: { lat: 26.8932, lng: 75.8018 },
    adjacentZones: ['corridor-north', 'food-north', 'restroom-north'],
    lastUpdated: Date.now(),
  },
  {
    id: 'stand-south',
    name: 'South Stand',
    type: 'seating',
    capacity: 5000,
    currentOccupancy: 2800,
    predictedOccupancy: 3500,
    status: 'moderate',
    predictedStatus: 'moderate',
    waitTime: 0,
    predictedWaitTime: 0,
    congestionTrend: 'rising',
    riskScore: 0.56,
    coordinates: { lat: 26.8912, lng: 75.8018 },
    adjacentZones: ['corridor-south', 'food-south', 'restroom-south'],
    lastUpdated: Date.now(),
  },
  {
    id: 'stand-east',
    name: 'East Pavilion',
    type: 'seating',
    capacity: 4000,
    currentOccupancy: 3600,
    predictedOccupancy: 3800,
    status: 'crowded',
    predictedStatus: 'critical',
    waitTime: 0,
    predictedWaitTime: 0,
    congestionTrend: 'rising',
    riskScore: 0.9,
    coordinates: { lat: 26.8922, lng: 75.8035 },
    adjacentZones: ['corridor-east', 'food-east'],
    lastUpdated: Date.now(),
  },
  {
    id: 'vip-lounge',
    name: 'VIP Lounge',
    type: 'vip_lounge',
    capacity: 300,
    currentOccupancy: 90,
    predictedOccupancy: 120,
    status: 'clear',
    predictedStatus: 'moderate',
    waitTime: 0,
    predictedWaitTime: 2,
    congestionTrend: 'rising',
    riskScore: 0.3,
    coordinates: { lat: 26.8926, lng: 75.8000 },
    adjacentZones: ['gate-d', 'corridor-west'],
    lastUpdated: Date.now(),
  },
  {
    id: 'food-north',
    name: 'North Food Court',
    type: 'food_court',
    capacity: 600,
    currentOccupancy: 420,
    predictedOccupancy: 520,
    status: 'crowded',
    predictedStatus: 'critical',
    waitTime: 15,
    predictedWaitTime: 22,
    congestionTrend: 'rising',
    riskScore: 0.7,
    coordinates: { lat: 26.8936, lng: 75.8025 },
    adjacentZones: ['stand-north', 'corridor-north', 'restroom-north'],
    lastUpdated: Date.now(),
  },
  {
    id: 'food-south',
    name: 'South Food Court',
    type: 'food_court',
    capacity: 500,
    currentOccupancy: 180,
    predictedOccupancy: 250,
    status: 'moderate',
    predictedStatus: 'moderate',
    waitTime: 5,
    predictedWaitTime: 8,
    congestionTrend: 'rising',
    riskScore: 0.36,
    coordinates: { lat: 26.8906, lng: 75.8025 },
    adjacentZones: ['stand-south', 'corridor-south'],
    lastUpdated: Date.now(),
  },
  {
    id: 'food-east',
    name: 'East Food Stalls',
    type: 'food_court',
    capacity: 350,
    currentOccupancy: 100,
    predictedOccupancy: 140,
    status: 'clear',
    predictedStatus: 'moderate',
    waitTime: 3,
    predictedWaitTime: 5,
    congestionTrend: 'rising',
    riskScore: 0.29,
    coordinates: { lat: 26.8918, lng: 75.8042 },
    adjacentZones: ['stand-east', 'corridor-east'],
    lastUpdated: Date.now(),
  },
  {
    id: 'restroom-north',
    name: 'North Restrooms',
    type: 'restroom',
    capacity: 150,
    currentOccupancy: 110,
    predictedOccupancy: 130,
    status: 'crowded',
    predictedStatus: 'critical',
    waitTime: 10,
    predictedWaitTime: 15,
    congestionTrend: 'rising',
    riskScore: 0.73,
    coordinates: { lat: 26.8938, lng: 75.8015 },
    adjacentZones: ['food-north', 'stand-north', 'corridor-north'],
    lastUpdated: Date.now(),
  },
  {
    id: 'restroom-south',
    name: 'South Restrooms',
    type: 'restroom',
    capacity: 150,
    currentOccupancy: 60,
    predictedOccupancy: 80,
    status: 'moderate',
    predictedStatus: 'moderate',
    waitTime: 4,
    predictedWaitTime: 6,
    congestionTrend: 'stable',
    riskScore: 0.4,
    coordinates: { lat: 26.8905, lng: 75.8015 },
    adjacentZones: ['stand-south', 'corridor-south'],
    lastUpdated: Date.now(),
  },
  {
    id: 'corridor-north',
    name: 'North Corridor',
    type: 'corridor',
    capacity: 800,
    currentOccupancy: 350,
    predictedOccupancy: 500,
    status: 'moderate',
    predictedStatus: 'crowded',
    waitTime: 3,
    predictedWaitTime: 7,
    congestionTrend: 'rising',
    riskScore: 0.44,
    coordinates: { lat: 26.8934, lng: 75.8012 },
    adjacentZones: ['gate-a', 'stand-north', 'food-north', 'restroom-north', 'corridor-east', 'corridor-west'],
    lastUpdated: Date.now(),
  },
  {
    id: 'corridor-south',
    name: 'South Corridor',
    type: 'corridor',
    capacity: 800,
    currentOccupancy: 200,
    predictedOccupancy: 300,
    status: 'clear',
    predictedStatus: 'moderate',
    waitTime: 1,
    predictedWaitTime: 3,
    congestionTrend: 'rising',
    riskScore: 0.25,
    coordinates: { lat: 26.8910, lng: 75.8012 },
    adjacentZones: ['gate-c', 'stand-south', 'food-south', 'restroom-south', 'corridor-east', 'corridor-west'],
    lastUpdated: Date.now(),
  },
  {
    id: 'corridor-east',
    name: 'East Corridor',
    type: 'corridor',
    capacity: 600,
    currentOccupancy: 420,
    predictedOccupancy: 500,
    status: 'crowded',
    predictedStatus: 'critical',
    waitTime: 8,
    predictedWaitTime: 14,
    congestionTrend: 'rising',
    riskScore: 0.7,
    coordinates: { lat: 26.8922, lng: 75.8038 },
    adjacentZones: ['gate-b', 'stand-east', 'food-east', 'corridor-north', 'corridor-south'],
    lastUpdated: Date.now(),
  },
  {
    id: 'corridor-west',
    name: 'West Corridor',
    type: 'corridor',
    capacity: 600,
    currentOccupancy: 150,
    predictedOccupancy: 200,
    status: 'clear',
    predictedStatus: 'clear',
    waitTime: 1,
    predictedWaitTime: 2,
    congestionTrend: 'stable',
    riskScore: 0.25,
    coordinates: { lat: 26.8922, lng: 75.8002 },
    adjacentZones: ['gate-d', 'vip-lounge', 'corridor-north', 'corridor-south'],
    lastUpdated: Date.now(),
  },
  {
    id: 'parking-a',
    name: 'Parking Lot A',
    type: 'parking',
    capacity: 1000,
    currentOccupancy: 750,
    predictedOccupancy: 900,
    status: 'crowded',
    predictedStatus: 'critical',
    waitTime: 8,
    predictedWaitTime: 15,
    congestionTrend: 'rising',
    riskScore: 0.75,
    coordinates: { lat: 26.8945, lng: 75.8000 },
    adjacentZones: ['gate-a'],
    lastUpdated: Date.now(),
  },
  {
    id: 'parking-b',
    name: 'Parking Lot B',
    type: 'parking',
    capacity: 800,
    currentOccupancy: 300,
    predictedOccupancy: 400,
    status: 'moderate',
    predictedStatus: 'moderate',
    waitTime: 3,
    predictedWaitTime: 5,
    congestionTrend: 'rising',
    riskScore: 0.38,
    coordinates: { lat: 26.8918, lng: 75.8050 },
    adjacentZones: ['gate-b'],
    lastUpdated: Date.now(),
  },
  {
    id: 'parking-c',
    name: 'Parking Lot C',
    type: 'parking',
    capacity: 600,
    currentOccupancy: 180,
    predictedOccupancy: 220,
    status: 'clear',
    predictedStatus: 'moderate',
    waitTime: 1,
    predictedWaitTime: 3,
    congestionTrend: 'rising',
    riskScore: 0.3,
    coordinates: { lat: 26.8900, lng: 75.8025 },
    adjacentZones: ['gate-c'],
    lastUpdated: Date.now(),
  },
];
